-- TokkiTalk MEMBER 테이블 생성
CREATE TABLE MEMBER (
    ID VARCHAR2(20) PRIMARY KEY,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE
);

-- 테이블 생성 확인
SELECT * FROM MEMBER;

-- 샘플 데이터 삽입 (테스트용)
INSERT INTO MEMBER (ID, PW, NAME, EMAIL, PHONE) 
VALUES ('test', '1234', '테스트', 'test@test.com', '010-1234-5678');

-- 데이터 확인
SELECT * FROM MEMBER;

-- Analyses table for conversation analysis results
CREATE TABLE analyses (
  analysis_id       VARCHAR2(64) PRIMARY KEY,
  literal_summary   VARCHAR2(300),
  implied_intent    VARCHAR2(200),
  risk_flags        VARCHAR2(300),
  emotion_label     VARCHAR2(20),
  emotion_valence   NUMBER(2),
  emotion_arousal   NUMBER(3,2),
  politeness_level  VARCHAR2(20),
  cues_json         CLOB,
  suggestion_main   VARCHAR2(500),
  suggestion_alt    CLOB,
  suggestion_tone   VARCHAR2(20),
  rationale         VARCHAR2(500),
  overall_confidence NUMBER(3,2),
  model_version     VARCHAR2(40)
);

CREATE TABLE analysis_feedback (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id      VARCHAR2(64) NOT NULL,
  liked            NUMBER(1),
  partner_reaction VARCHAR2(100),
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);