-- TokkiTalk MEMBER 테이블 생성
CREATE TABLE MEMBER (
    ID VARCHAR2(20) PRIMARY KEY,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE
);

-- 테이블 생성 확인
SELECT * FROM MEMBER;

-- 샘플 데이터 삽입 (테스트용)
INSERT INTO MEMBER (ID, PW, NAME, EMAIL, PHONE) 
VALUES ('test', '1234', '테스트', 'test@test.com', '010-1234-5678');

-- 데이터 확인
SELECT * FROM MEMBER;
